const abtnsdesc = {"1-1a Introduction - Previous Lesson": "test",
"1-1b Introduction - This Lesson": "test",
"1-3 Grammar Notes": "test",
"1-6 Lesson Test": "test",
"1-7 Lesson 1 Homework": "test",
"4-h1": "Sion & Ffion",
"4-h2": "Pedr & Sianed",
"1-h2": "Alphabet",
"1-h3": "Dipthongs",
"2-h1": "First 28 words",
"3-h1": "First 28 words",
"3-h2": "Initiators & Connectors",
"3-h3": "Prepositions",
"3-h4": "Comprehension Story",
"1-h1": "Speech Parts",
"a-h1": "test",
"a-h2": "test",
"2-h1a": "Y Teulu Prys 1",
"2-h1b": "Y Teulu Prys 2",
"2-h1c": "Y Teulu Prys 3",
"2-h1d": "Y Teulu Prys 4",
"2-h1e": "Y Teulu Prys 5",
"2-h1f": "Y Teulu Prys 6",
"b-h1": "A Mysterious Phone Call A",
"b-h2": "A Mysterious Phone Call Vocab",
"b-h3": "A Mysterious Phone Call B",
"4-h3": "Idioms & Exclamations",
"4-h4": "Story Rewrite",
};