const abtnsdesc = {"1-1a Introduction - Previous Lesson": "",
"1-1b Introduction - This Lesson": "",
"1-3 Grammar Notes": "",
"1-6 Lesson Test": "",
"1-7 Lesson 1 Homework": "",
"4-h1": "Sion and Ffion",
"4-h2": "Pedr and Sianed",
"1-h2": "Alphabet",
"1-h3": "Dipthongs",
"2-h1": "First 28 words",
"2-h1b": "First 28 words",
"3-h1": "Pronouns & Initiators",
"3-h1b": "Pronouns & Initiators",
"3-h2": "Initiators & Connectors",
"3-h2b": "Initiators & Connectors",
"3-h3": "Initiators & Connectors",
"3-h3b": "Initiators & Connectors",
"3-h4": "Initiators & Connectors",
"1-h1": "speech parts",
"a-h1": "speech parts",
"a-h2": "speech parts",
"2-h1a": "speech parts",
"2-h1b": "speech parts",
"2-h1c": "speech parts",
"2-h1d": "speech parts",
"2-h1e": "speech parts",
"2-h1f": "speech parts",
"b-h1": "speech parts",
"b-h2": "speech parts",
"b-h3": "speech parts",
"4-h3": "speech parts",
};